version: '3'

services:
  inventory_db:
    image: postgres:latest
    container_name: inventory_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_db
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - inventory_data:/var/lib/postgresql/data/ 

volumes:
  inventory_data: